### PR TITLE
Create spanish.md

### PR DESCRIPTION
**Pull request by nehasangeetajha**
Solves Issue #1 
Added new file for Spanish language
Added Contributors file

### CODE REVIEW

**Comment by nehasangeetajha** [comment]
Solves Issue #1

**Review by avhhh — CHANGES_REQUESTED** [review]
Please change the name table of contents to "index.md" as mentioned in the issue

**Comment by nehasangeetajha** [comment]
Done

**Review by avhhh — APPROVED** [review]

**Review by AnnuJoshi — APPROVED** [review]
Thank you Sangeeta! Great Work!

**Comment by nehasangeetajha** [comment]
Thank you so much

**Pull request closed without merging**
